Build Requirements
---------
Ubuntu 24.04 installed with:

build-essential, cmake, libjsoncpp-dev, uuid-dev, orthanc-dev

docker that your user/group id can use. Go to docker.io to
see how toset that up.

Build steps
--------
1. mkdir Build
2. cd Build
3. ../Resources/CreateOHIFDist.sh
4. cmake .. -DSTATIC_BUILD=ON -DCMAKE_BUILD_TYPE=Release
5. make
