#!/bin/bash
monly=0
#
# Given a Study UUID, get the modality from the first instance from the first series
#
if [[ $# -eq 0 ]]; then
 list=$(curl -s  http://localhost:8042/studies|jq -r '.[]')
else
 if [[ $1 == "-r" ]]; then
  monly=1
  shift
 fi
 if [[ $# -eq 0 ]]; then
  list=$(curl -s  http://localhost:8042/studies|jq -r '.[]')
 else
  list=$*
 fi
fi
ct=0
for entry in $list; do
 STUDY_UUID=$entry
 SESSION=$(curl -s  http://localhost:8042/studies/$STUDY_UUID |jq  -r '.MainDicomTags.AccessionNumber')
 if [[ -z "$SESSION" ]]; then
  SESSION=NULL
 fi
 MRN=$(curl -s  http://localhost:8042/studies/$STUDY_UUID |jq -r '.PatientMainDicomTags.PatientID')
 if [[ -z "$MRN" ]]; then
  MRN=NULL
 fi
 SERIES_UUID=$(curl -s http://localhost:8042/studies/$STUDY_UUID |jq -r .Series[0])
 MODALITY=$(curl -s  http://localhost:8042/series/$SERIES_UUID | jq -r .MainDicomTags.Modality)
 if [[ $ct -eq 0 && $monly -eq 0 ]]; then
  printf "%-45s %8s %-s\n" "Study" "Modality" "Session/MRN"
 fi
 if [[ $monly -eq 0 ]]; then
  printf "%-45s %-8s %s/%s\n" $STUDY_UUID $MODALITY "$SESSION" "$MRN"
 else
  echo $MODALITY
 fi
 ct=$((ct + 1))
done
