#!/usr/bin/python3
#
# Program to put up a set up of menus about selecting studies to operate on
#

import tkinter as tk
from tkinter import messagebox
import os
import fcntl
import json
import requests
import subprocess
import argparse
import logging

""" Variables and Constants """
REPORTDIR = "/code_dark/reports"
LOG = "/code_dark/logs/study_tool.log"
STUDYURL = "http://localhost:8042/studies"
THIS_STUDY_URL_PREFIX = "http://localhost:8042/app/explorer.html#study?uuid="
PATIENT_COL = 0
MRN_COL = 1
SESSION_NUMBER_COL = 2
STUDY_DESCRIPTION_COL = 3
STUDY_DATE_COL = 4
LAST_DICOM_DATA_COL = STUDY_DATE_COL

browser = "firefox"
NoStudies = "No such studies"
NoStudiesPresent = "No studies present"
CannotReview = "Cannot Open"
StudiesToReview = "Studies To Begin Reviewing"
StudiesToEdit = "Studies to Continue Reviewing"
StudiesToSign = "Studies ready to sign"
StudiesToPrint = "Signed studies ready to print"
DeleteUnsigned = "Delete started but unsigned reports"
ListAllStudies = "List All Studies"

fontsize = 12
fontfamily = "Times"

#
# Process command line arguments if any
#
parser = argparse.ArgumentParser(description="Code Dark Report Entry Package")
parser.add_argument("-b", "--browser", help="which web browser to user")
parser.add_argument("-f", "--fontsize", help="Font Size (default 12)")
args = vars(parser.parse_args())
if args['fontsize']:
    fontsize = int(args['fontsize'])
if args['browser']:
    browser = int(args['browser'])

logging.basicConfig(filename=LOG, filemode="a", encoding="utf-8", format="{asctime} - {levelname} - {message}",
    style="{", datefmt="%m/%d/%Y %H:%M", level=logging.INFO)
logger = logging.getLogger(__name__)
logger.info("Code Dark Study Tool started")

""" Button handlers """
def show_dicom(uuid, js):
    sw = tk.Tk()
    sw.title(uuid + " DICOM data")
    txt = tk.Text(sw, height=40, width=80)
    scroll = tk.Scrollbar(sw)
    txt.configure(yscrollcommand=scroll.set)
    txt.pack(side=tk.LEFT)
    txt.insert(tk.END, json.dumps(js, indent=2))
    sw.mainloop()

""" Study Table construction and presentation """
#
#
# Present the passed array of studies as a table with the passed title
# 
# To the right of each table entry is a set of action buttons (still to be formalized)
#
def present_table(title, ulist, button_creator):
    header = False
    nr = tk.Tk()
    nr.title(title)
    rowvar = 1

    for suuid in ulist:
        srsp = requests.get(STUDYURL + "/" + suuid)
        if srsp.status_code != 200:
            continue

        try:
            result = subprocess.run(["GetStudyDate", "-r", suuid], capture_output=True, text=True)
            if result.returncode != 0:
                logger.warning("cannot get study date for" + suuid + ":", result.returnconde)
                continue
        except subprocess.CalledProcessError as e:
            logger.error("Error getting study date for" + suuid + ":", e.output)
            continue
        dst = result.stdout.strip()
        sjsn = srsp.json()
        patient = sjsn["PatientMainDicomTags"]
        maindcm = sjsn["MainDicomTags"]
        for pk in "PatientName","PatientID":
            try:
                s = patient[pk]
            except:
                patient[pk] = "<NIL>"
        for dk in "AcessionNumber":
            try:
                s = maindcm[dk]
            except:
                maindcm[dk] = "<NIL>"

        if header == False:
            x = tk.Entry(nr, font=(fontfamily,fontsize,'bold'))
            x.grid(row=rowvar, column=PATIENT_COL)
            x.insert(tk.END, "Patient Name")

            x = tk.Entry(nr, font=(fontfamily,fontsize,'bold'))
            x.grid(row=rowvar, column=MRN_COL)
            x.insert(tk.END, "MRN")

            x = tk.Entry(nr, font=(fontfamily,fontsize,'bold'))
            x.grid(row=rowvar, column=SESSION_NUMBER_COL)
            x.insert(tk.END, "Session Number")

            x = tk.Entry(nr, width=20, font=(fontfamily,fontsize,'bold'))
            x.grid(row=rowvar, column=STUDY_DESCRIPTION_COL)
            x.insert(tk.END, "Study Description")

            x = tk.Entry(nr, width=30, font=(fontfamily,fontsize,'bold'))
            x.grid(row=rowvar, column=STUDY_DATE_COL)
            x.insert(tk.END, "Study Date")

            """ XXX Need a "state" column here of where we are with this study """

            header = True
            rowvar = rowvar + 1

        """ Constant study related columns """
        x = tk.Entry(nr,font=(fontfamily,fontsize))
        x.grid(row=rowvar, column=PATIENT_COL)
        x.insert(tk.END, patient["PatientName"])

        x = tk.Entry(nr,font=(fontfamily,fontsize))
        x.grid(row=rowvar, column=MRN_COL)
        x.insert(tk.END, patient["PatientID"])

        x = tk.Entry(nr,font=(fontfamily,fontsize))
        x.grid(row=rowvar, column=SESSION_NUMBER_COL)
        x.insert(tk.END, maindcm["AccessionNumber"])

        try:
            sdesc = maindcm["StudyDescription"]
        except:
            sdesc = ""

        x = tk.Entry(nr, width=20, font=(fontfamily,fontsize))
        x.grid(row=rowvar, column=STUDY_DESCRIPTION_COL)
        x.insert(tk.END, sdesc)

        x = tk.Entry(nr, width=30, font=(fontfamily,fontsize))
        x.grid(row=rowvar, column=STUDY_DATE_COL)
        x.insert(tk.END, dst)

        """ Action buttons """
        col = LAST_DICOM_DATA_COL + 1
        x = tk.Button(nr, text = 'Show DICOM', width = 10, command = lambda u = suuid, j = sjsn : show_dicom(u, j))
        x.grid(sticky=tk.W, column=col, row=rowvar)
        col = col + 1

        if button_creator != None:
            button_creator(suuid, nr, col, rowvar)

        rowvar = rowvar + 1

    nr.mainloop()

def edit_report(uuid):
    print("edit_report for " + str(uuid))
    logger.info("edit_report for " + str(uuid))
    print("spawning browser")
    logger.info("spawning browser")
    os.spawnlp(os.P_NOWAIT, browser, browser, THIS_STUDY_URL_PREFIX + str(uuid))
    print("spawning code_dark_rptgen")
    logger.info("spawning code_dark_rptgen")
    os.spawnlp(os.P_NOWAIT, "code_dark_rptgen", "code_dark_rptgen", "-j", REPORTDIR + "/" + str(uuid) + ".json")
    print("leaving edit_report")
    logger.info("leaving edit_report")

def edit_button_add(uui, nr, col, row):
    x = tk.Button(nr, text = 'Edit Study Report', width = 20, command = lambda u = uui : edit_report(u))
    x.grid(sticky=tk.W, column=col, row=row)

def review_study(uuid):
    print("review_study for " + str(uuid))
    logger.info("review_study for " + str(uuid))
    print("spawning browser")
    logger.info("spawning browser")
    os.spawnlp(os.P_NOWAIT, browser, browser, THIS_STUDY_URL_PREFIX + str(uuid))
    print("levaing review_study", result)
    logger.info("levaing review_study", result)

def review_button_add(uui, nr, col, row):
    x = tk.Button(nr, text = 'Begin Review', width = 12, command = lambda u = uui : review_study(u))
    x.grid(sticky=tk.W, column=col, row=row)

def studies_to_review():
    """
    Begin review of studies that haven't been reviewed yet

    A study is in this state if there is no <UUID>.json in /code_dark/reports.
    We have not looked at it at all.
    """
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        messagebox.showerror(message=NoStudiesPresent)
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile) is False:
            out.append(uu)
    ns = len(out)
    if ns == 0:
        messagebox.showinfo("", NoStudies)
    elif ns == 1:
        present_table("One Study to begin reviewing", out, review_button_add)
    else:
        present_table(str(ns) + " Studies to begin reviewing", out, review_button_add)

def studies_to_edit():
    """
    Continue review of studies that have been reviewed at least partially already.

    A study is in this state if there is a <UUID>.json in /code_dark/reports and
    loading data from that json indicates that the study has not been signed.
    """
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        messagebox.showerror("Cannot find any studies at all!")
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile):
            """ Now load report data the file for this study """
            json_data = []
            with open(jsfile, "r") as infile:
                json_data = json.load(infile)
            if not json_data["signed"]:
                out.append(uu)
    ns = len(out)
    if ns == 0:
        messagebox.showinfo("", NoStudies)
    elif ns == 1:
        present_table("One Study to continue reviewing", out, edit_button_add)
    else:
        present_table(str(ns) + " Studies to continue reviewing", out, edit_button_add)

def studies_to_sign():
    """
    Find studies which are ready to sign as a list.

    A study is in this state if there is a <UUID>.json in /code_dark/reports and
    loading data from that json indicates that the study has met the criteria
    for being signed. The first criteria is that it isn't now signed!
    """
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        messagebox.showerror(message=NoStudiesPresent)
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile):
            """ Now load report data the file for this study """
            json_data = []
            with open(jsfile, "r") as infile:
                json_data = json.load(infile)
            if not json_data["signed"]:
                """ XXX GET OTHER CRITERIA- MAYBE HAVE AN EXTERNAL SCRIPT TO USE XXX """
                if json_data["signer"] != "":
                    out.append(uu)
    ns = len(out)
    if ns == 0:
        messagebox.showinfo("", NoStudies)
    elif ns == 1:
        present_table("One Study ready for signing", out, None)
    else:
        present_table(str(ns) + " Studies ready for signing", out, None)

def studies_to_print():
    """
    Find studies which are ready to print.

    A study is in this state if there is a <UUID>.json in /code_dark/reports and
    loading data from that json indicates that the study has been signed
    but not printed.
    """
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        messagebox.showerror(message=NoStudiesPresent)
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile):
            """ Now load report data the file for this study """
            json_data = []
            with open(jsfile, "r") as infile:
                json_data = json.load(infile)
            if json_data["signed"]:
                # Handle an older database which doesn't have the printed key
                try:
                    if not json_data["printed"]:
                        out.append(uu)
                except:
                    # If we don't have the printed key we'll assume it hasn't been printed
                    out.append(uu)
    ns = len(out)
    if ns == 0:
        messagebox.showinfo("", NoStudies)
    elif ns == 1:
        present_table("One signed study ready for printing", out, None)
    else:
        present_table(str(ns) + " studies ready for printing", out, None)

def delete_report(uuid):
    print("delete_report for " + str(uuid))
    logger.info("delete_report for " + str(uuid))
    jsfile = REPORTDIR + "/" + str(uuid) + ".json"
    try:
        f = open(jsfile, "r")
    except FileNotFoundError:
        print("file", jsfile, "not found")
        logger.warning("file " + jsfile + " not found")
        messagebox.showerror(title="Error", message="Report File not found")
        return
    except Exception as e:
        print(f"exception: {e}")
        messagebox.showerror(title="Error", message="File Error")
        return
    # Make sure it isn't currently being edited
    lockfname = "/dev/shm/" + uuid + ".lock"
    locket = open(lockfname, "a")
    try:
        fcntl.flock(locket.fileno(), fcntl.LOCK_NB + fcntl.LOCK_EX);
    except OSError as e:
        if e.errno == errno.EACCES or e.errno == errno.EAGAIN:
            print(uuid, "already being edited")
            messagebox.showerror("Error", "Study being edited")
        else:
            print(f"lock error {e}")
            messagebox.showerror("Error", "Cannot access")
        f.close()
        locket.close()
        return
    os.unlink(jsfile)
    f.close()
    fcntl.flock(locket.fileno(), fcntl.LOCK_UN)
    locket.close()

def delete_button_add(uui, nr, col, row):
    x = tk.Button(nr, text = 'Delete Report', width = 20, command = lambda u = uui : delete_report(u))
    x.grid(sticky=tk.W, column=col, row=row)

def studies_to_delete():
    """
    List studies that have been started but have not been signed and put
    up a button to delete any reports in progess.

    A study is in this state if there is a <UUID>.json in /code_dark/reports and
    loading data from that json indicates that the study has not been signed.
    """
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        messagebox.showerror("Cannot find any studies at all!")
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile):
            """ Now load report data the file for this study """
            json_data = []
            with open(jsfile, "r") as infile:
                json_data = json.load(infile)
            if not json_data["signed"]:
                out.append(uu)
    ns = len(out)
    if ns == 0:
        messagebox.showinfo("", NoStudies)
        return
    elif ns == 1:
        present_table("One possible report to delete", out, delete_button_add)
    else:
        present_table(str(ns) + " possible reports to delete", out, delete_button_add)

def all_studies():
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        messagebox.showerror(title="Error", message="Cannot find any studies at all!")
        return
    sulist = response.json()
    present_table("All " + str(len(sulist)) + " Studies", sulist, None)

""" Begin Main Code section """

root=tk.Tk()
root.title("Code Dark Study Tool")
root.minsize(width=300, height=150)

btn = tk.Button(root, text=StudiesToReview, command=studies_to_review)
btn.grid(sticky=tk.W+tk.N, row=5, column=0)

btn = tk.Button(root, text=StudiesToEdit, command=studies_to_edit)
btn.grid(sticky=tk.W+tk.N, row=6, column=0)

btn = tk.Button(root, text=StudiesToSign, command=studies_to_sign)
btn.grid(sticky=tk.W+tk.N, row=7, column=0)

btn = tk.Button(root, text=StudiesToPrint, command=studies_to_print)
btn.grid(sticky=tk.W+tk.N, row=8, column=0)

btn = tk.Button(root, text=DeleteUnsigned, command=studies_to_delete)
btn.grid(sticky=tk.W+tk.N, row=9, column=0)

btn = tk.Button(root, text=ListAllStudies, command=all_studies)
btn.grid(sticky=tk.W+tk.N, row=10, column=0)

root.mainloop()
