#!/bin/sh
set -e

#
# Clean up permissions
#
chown root:root /etc/sudoers.d/orthanc
chmod 600 /etc/sudoers.d/orthanc

#
# Install Desktop entries
#
install -D -m 755 -o orthanc /usr/share/applications/code_dark_configurator.desktop ~orthanc/Desktop
install -D -m 755 -o orthanc /usr/share/applications/code_dark_study_tool.desktop ~orthanc/Desktop
install -D -m 755 -o orthanc /usr/share/applications/code_dark_about.desktop ~orthanc/Desktop

#
# Make sure initial config file setup has been completed
#
for subdir in config/orthanc reports logs; do mkdir -p /code_dark/$subdir; done
if [ ! -f /code_dark/config/configurator.json ]; then
 cp /usr/share/cdpw/configurator.json /code_dark/config
 cp /usr/share/cdpw/cdpw.json /code_dark/config/orthanc
 cp /usr/share/cdpw/dicom_aet_port.json /code_dark/config/orthanc
 chown -R orthanc:orthanc /code_dark
fi

#
# Install AET port parameters in orthanc's config directory if not already there
# and make sure that the original in the main config is removed.
#
if [ ! -f /etc/orthanc/dicome_aet_port.json ]; then
 cp /usr/share/cdpw/dicom_aet_port.json /etc/orthanc
 sed -i -e '/  "DicomAet/d' -e '/  "DicomPort/d' /etc/orthanc/orthanc.json 
fi
