#!/bin/sh
set -e

case $1 in
remove|purge)
 rm -f ~orthanc/Desktop/code_dark_configurator.desktop
 rm -f ~orthanc/Desktop/code_dark_study_tool.desktop
 sed -i -e '/CODE_DARK/d' /etc/fstab
 systemctl daemon-reload
 ;;
upgrade)
 systemctl restart cdpw_data_present.service
 ;;
esac

