#!/bin/sh

#
# Stop our systemd version of orthanc if we are removing.
# Unmount /CODE_DARK if we are removing
#
if [ "$1" = "remove" ]; then
 systemctl is-active --quiet cdpw.service && systemctl stop cdpw.service && pkill orthanc_checker
 lsmount | grep -q code_dark && umount /code_dark
 systemctl is-active --quiet cdpw_data_present.service && systemctl stop cdpw_data_present.service
fi
exit 0
