#!/bin/bash

CFG=/code_dark/config/configurator.json
ORT=/etc/orthanc/orthanc.json
LOG=/tmp/CDPW.log
touch ${LOG} >/dev/null 2>&1 || LOG=/tmp/CDPW.log
echo CDPW_Configure starting on `date` >> $LOG

#
# Check for configuration database
# and make changes based upon what
# we find in it.
#
changed=no
if [[ -f $CFG ]]; then
 port=$(jq -r .dicom.port 2> /dev/null < $CFG)
 if [[ "$port" != "null" ]]; then
  DicomPort=$(grep 'DicomPort" :' /etc/orthanc/orthanc.json |sed -e 's/,//' -e 's/ //g' | awk -F: ' { print $2 }')
  if [[ $port != $DicomPort ]]; then
   echo Changing Dicom port from $DicomPort to $port >> $LOG
   sed -i -e "/DicomPort/c\\ \"DicomPort\" : ${port}," ${ORT}
   changed=yes
  fi
 fi
 aet=$(jq -r .dicom.aet 2> /dev/null < $CFG)
 if [[ "$aet" != "null" ]]; then
  DicomAet=$(grep 'DicomAet" :'  /etc/orthanc/orthanc.json  | sed -e 's/"//g' -e 's/ //g' -e 's/,//g'| awk -F: ' { print $2 }')
  if [[ $aet != $DicomAet ]]; then
   echo Changing Dicom AET from $DicomAet to $aet >> $LOG
   sed -i -e "/DicomAet\" :/c\\ \"DicomAet\" : \"${aet}\"," ${ORT}
   changed=yes
  fi
 fi
fi
#
# Change database directory to code_dark
#
grep -q /var/lib/orthanc/db-v6 ${ORT}
if [[ $? -eq 0 ]]; then
 echo setting orthanc database to /code_dark/database >> $LOG
 if [[ ! -f ${ORT}.save ]]; then
  cp ${ORT} ${ORT}.save
 fi
 sed -i 's,/var/lib/orthanc/db-v6,/code_dark/database,' ${ORT}
 changed="yes"
fi

#
# If we made any actual changes, restart Orthanc
#
if [[ $changed == "yes" ]]; then
 echo restarting orthanc >> $LOG
 systemctl daemon-reload
 systemctl restart orthanc >> $LOG 2>&1
fi
