#!/bin/bash

#
# systemd-udev calls this script so we can mount our
# secure storage key when it appears.
#


#
# Validate args
#
if [[ $# -ne 2 ]]; then
 exit 0
fi
case $1 in
 mount|unmount);;
 *) exit 0;;
esac
case $2 in
 /dev/sd*) ;;
 *) exit 0 ;;
esac

DEV=$2

#
# Fetch orthanc's uid/gid from the password file.
#
# If they aren't present, then we assume orthanc isn't installed
# so we do nothing.
#
ORTHANC_UID=$(grep orthanc /etc/passwd 2> /dev/null|awk -F: '{print $3}')
if [[ -z "${ORTHANC_UID}" ]]; then
 exit 0
fi

#
# Set some parameters
#
D_MNT=/var/lib/orthanc/db-v6
M_OPTS="--no-pager --no-legend --collect --no-block"

#
# just in case- we need it stopped first whether we are mounting or unmounting
#
systemctl stop orthanc

if [[ $1 == "mount" ]]; then
 /usr/bin/systemd-mount ${M_OPTS} -t ntfs-3g --options="noatime,uid=${ORTHANC_UID},hide_hid_files,umask=0,dmask=27,fmask=137" ${DEV} ${D_MNT} >> /tmp/om.log 2>&1
 systemctl start orthanc >> /tmp/om.log 2>&1
else
 /usr/bin/systemd-umount ${D_MNT}
fi
