#!/bin/bash

#
# Change Dicom Port if there is a file containing a new port number in it.
#
port=
if [[ -f /code_dark/config/dicomport ]]; then
 port=$(cat /code_dark/config/dicomport)
fi
if [[ -n "$port" ]]; then
 echo changing Dicom port to $port
 sed -i -e "/DicomPort/c\\ \"DicomPort\" : ${port}," /etc/orthanc/orthanc.json
 systemctl restart orthanc
fi

#
# Change database directory to code_dark
#
sed -i 's,/var/lib/orthanc/db-v6,/code_dark/database,' /etc/orthanc/orthanc.json
