#!/bin/bash
export XDG_RUNTIME_DIR=/run/user/$UID
export DISPLAY=:0
LONG_SLEEP=600
SHRT_SLEEP=10
SHRT_MSECS=$((((SHRT_SLEEP - 2)) * 1000))
set -o pipefail
while :; do
 df | grep -q /code_dark
 if [[ $? -ne 0 ]]; then
  echo Data storage device not mounted- sleeping $SHRT_SLEEP seconds
  notify-send  -t $SHRT_MSECS -a Orthanc 'Orthanc Cannot Start' \
   'Secure data storage device not seen- still locked?'
  stime=$SHRT_SLEEP
 else
  echo Data device mounted- sleeping $LONG_SLEEP seconds
  stime=$LONG_SLEEP
 fi
 sleep $stime
done
