#!/bin/bash
export XDG_RUNTIME_DIR=/run/user/$UID
export DISPLAY=:0
LONG_SLEEP=600
SHRT_SLEEP=10
SHRT_MSECS=$((((SHRT_SLEEP - 2)) * 1000))
set -o pipefail
while :; do
 sudo -n mount /code_dark > /dev/null 2>&1
 df | grep -q /code_dark
 if [[ $? -ne 0 ]]; then
  echo Data storage device not mounted- sleeping $SHRT_SLEEP seconds
  notify-send  -t $SHRT_MSECS -a Orthanc 'Orthanc Cannot Start' \
   'Secure data storage device not seen- still locked?'
  stime=$SHRT_SLEEP
 else
  #
  # Make sure that code_dark directories are populated correctly
  # and initial configurator json is in place.
  #
  mkdir -p /code_dark/config /code_dark/database /code_dark/reports /code_dark/logs
  if [[ ! -f /code_dark/config/configurator.json ]]; then
   cp /usr/lib/kp-report/configurator.json /code_dark/config
  fi
  nor=$(ps ax | grep -w Orthanc | grep -v grep | wc -l)
  if [[ $nor -eq 0 ]]; then
   echo "Restarting orthanc because it is not running"
   sudo -n /usr/bin/restart_orthanc
  fi
  echo Data device mounted- sleeping $LONG_SLEEP seconds
  stime=$LONG_SLEEP
 fi
 sleep $stime
done
