#!/bin/bash
monly=0
#
# Given a Study UUID, get the Study Description from the main dicom tags
#
if [[ $# -eq 0 ]]; then
 list=$(curl -s  http://localhost:8042/studies|jq -r '.[]')
else
 if [[ $1 == "-r" ]]; then
  monly=1
  shift
 fi
 if [[ $# -eq 0 ]]; then
  list=$(curl -s  http://localhost:8042/studies|jq -r '.[]')
 else
  list=$*
 fi
fi
ct=0
for entry in $list; do
 STUDY_UUID=$entry
 STUDY_DESCRIPTION=$(curl -s  http://localhost:8042/studies/$STUDY_UUID |jq  -r .MainDicomTags.StudyDescription)
 if [[ -z "$STUDY_DESCRIPTION" ]]; then
  STUDY_DESCRIPTION=NULL
 fi
 if [[ $ct -eq 0 && $monly -eq 0 ]]; then
  printf "%-45s %40s\n" "Study" "StudyDescription"
 fi
 if [[ $monly -eq 0 ]]; then
  printf "%-45s %40s\n" $STUDY_UUID "$STUDY_DESCRIPTION"
 else
  echo $STUDY_DESCRIPTION
 fi
 ct=$((ct + 1))
done
