#!/bin/bash
#
# Get orthanc uid- needed to chown ~orthanc/.local additions
#
OUID=$(grep orthanc /etc/passwd 2> /dev/null|awk -F: '{print $3}')
if [[ -z "${OUID}" ]]; then
 # Hack.
 OUID=1000
fi

#
# Clean up permissions
#
chown root:root /etc/sudoers.d/orthanc
chown -R $OUID ~orthanc/.local

#
# Give orthanc the ability to bind to privileged ports
#
setcap 'cap_net_bind_service=+ep' /sbin/Orthanc

#
# Hand install symlinks to install our plugins into orthanc
#
rm -f /usr/share/orthanc/plugins/libReport.so
cd  /usr/share/orthanc/plugins && ln -s ../../../lib/kp-report/libReport.so.1.0 libReport.so
cd -
rm -f /usr/share/orthanc/plugins/libOrthancOHIF.so
cd  /usr/share/orthanc/plugins && ln -s ../../../lib/kp-report/libOrthancOHIF.so.1.4 libOrthancOHIF.so
cd -

#
# Install symlink to python tkinter time and date changer
#
mkdir -p ~orthanc/.local/share/applications
rm -f ~orthanc/.local/share/applications/SetSystemTime.desktop
cd  ~orthanc/.local/share/applications && ln -s /usr/lib/kp-report/SetSystemTime.desktop
cd -

#
# Enable cdw_configure service
#
systemctl enable cdw_configure.service
