#!/bin/bash

#
# Stop orthanc while we are changing what it will depend upon.
# Enable it- if it is installed as a dependency it seems
# to not automatically become enabled.
#
systemctl stop orthanc
systemctl enable orthanc

#
# Get orthanc's UID (needed for ntfs-3g mounts)
#
OUID=$(grep orthanc /etc/passwd 2> /dev/null|awk -F: '{print $3}')
if [[ -z "${OUID}" ]]; then
 # Hack.
 OUID=1000
fi

#
# Clean up permissions
#
chown root:root /etc/sudoers.d/orthanc
chown -R $OUID ~orthanc/.local

#
# Put the mount line we want in /etc/fstab
#
sed -i -e '/CODE_DARK/d' /etc/fstab
echo "LABEL=CODE_DARK /var/lib/orthanc/db-v6 ntfs-3g defaults,noatime,uid=${OUID},hide_hid_files,umask=0,dmask=27,fmask=137 0 0" >> /etc/fstab
systemctl daemon-reload

#
# Hand install symlinks to install our plugins into orthanc
#
rm -f /usr/share/orthanc/plugins/libReport.so
cd  /usr/share/orthanc/plugins && ln -s ../../../lib/kp-report/libReport.so.1.0 libReport.so
cd -
rm -f /usr/share/orthanc/plugins/libOrthancOHIF.so
cd  /usr/share/orthanc/plugins && ln -s ../../../lib/kp-report/libOrthancOHIF.so.1.4 libOrthancOHIF.so
cd -

#
# Install symlink to python tkinter time and date changer
#
mkdir -p ~orthanc/.local/share/applications
rm -f ~orthanc/.local/share/applications/SetSystemTime.desktop
cd  ~orthanc/.local/share/applications && ln -s /usr/lib/kp-report/SetSystemTime.desktop
cd -

#
# Kubuntu bug fixes we need.
#

#
# Clean up blank/black screen on reboot issue
#
grep -q 'splash' /etc/default/grub
if [[ $? -eq 0 ]]; then
 sed -i -e 's/splash//' /etc/default/grub
 update-grub > /dev/null 2>&1
fi
#
# Mask automatic ntp- we will be air-gapped.
#
systemctl stop systemd-timesyncd.service
systemctl mask systemd-timesyncd.service
