#!/bin/bash

#
# Get orthanc's UID (needed for ntfs-3g mounts)
#
OUID=$(grep orthanc /etc/passwd 2> /dev/null|awk -F: '{print $3}')
if [[ -z "${OUID}" ]]; then
 # Hack.
 OUID=1000
fi

#
# Make sure mount point exists
#
mkdir -p /code_dark

#
# Put the mount line we want in /etc/fstab
#
# Do this at preinst time so that orthanc reconfiguration
# does not get upset and fail during kp-report installation.
#
sed -i -e '/CODE_DARK/d' /etc/fstab
echo "LABEL=CODE_DARK /code_dark ntfs-3g defaults,noauto,noatime,uid=${OUID},hide_hid_files,umask=0,dmask=27,fmask=137,x-systemd.automount 0 0" >> /etc/fstab
systemctl daemon-reload
