#!/bin/bash
ORT=/etc/orthanc/orthanc.json

#
# Stop orthanc while we change things around
#

if [[ "$1" == "remove" ]]; then
 systemctl stop orthanc
 systemctl disable cdpw_configure.service
 umount /code_dark > /dev/null 2>&1
 sed -i -e '/CODE_DARK/d' /etc/fstab
 if [[ -f ${ORT}.save ]]; then
  mv ${ORT}.save ${ORT}
 fi
fi

#
# Do this for both remove and upgrade
#
if [[ -f /usr/lib/kp-report/idoc.txt ]]; then
 for i in  $(cat /usr/lib/kp-report/idoc.txt); do
  rm -f $i
 done
 rm -f /usr/lib/kp-report/idoc.txt
fi
rm -f /home/orthanc/Desktop/code_dark_configurator.desktop
