#!/bin/bash
#set -o pipefail

for i in $*; do
  mrn=$(2>/dev/null dcmdump -M +P 0010,0020 $i|col|egrep -v 'no value available|Anonimo|exam Number')
  ssn=$(2>/dev/null dcmdump -M +P 0008,0050 $i|col|egrep -v 'no value available|Anonimo|exam Number')
  if [[ -n "$ssn" && -n "$mrn"  ]]; then
   echo YES "$i"
  else
   echo NO " $i"
  fi
done
