#!/usr/bin/python3
#
# Program to configure some Code Dark workstation parameters.
#

import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk
import argparse
import datetime
import json
import subprocess
import sys
"""
We need to be able to configure the following items:

 DICOM
  Static Orthanc Port number to receive DICOM data
  Orthanc AET (Application Entity Title)

 Physicians

  Display a list of physicians who are authorized to sign reports.
  The list can be edited and in the edit box is a list of
  names separated by commas.

  NB: This mean no commas are allowed in physician names!

"""
""" Variables and Constants """
PT = "DicomPort"
AE = "DicomAet"
PH = "physicians"

cdpwconfig = "/code_dark/config"
jsonfile = cdpwconfig + "/" + "configurator.json"
aetpfile = cdpwconfig + "/" + "orthanc" + "/" + "dicom_aet_port.json"
vfile = "/usr/lib/cdpw/version"
cdw_version = ""
rowvar = 0
fontfamily = 'Times'
fontsize = 12
fontstring = fontfamily + ' ' + str(fontsize)
boxsize = 5

""" Argument Parsing """

parser = argparse.ArgumentParser(description="Code Dark Configurator")
parser.add_argument("-j", "--json", help="Input json file")
parser.add_argument("-a", "--aet_port", help="Dicom AET and Port json file")

args = vars(parser.parse_args())

if args['json']:
    jsonfile=args['json']

if args['aet_port']:
    aetpfile=args['aet_port']

try:
    with open(vfile) as ov:
        cdw_version = ov.readline()
except:
    pass

#
# Read in JSON saved data
#
with open(jsonfile, "r") as infile:
    json_data = json.load(infile)

with open(aetpfile, "r") as infile:
    aetp_data = json.load(infile)

#
# Version check
#
version = json_data["version"]
if version < 2:
    print("Version of JSON too low: ", version)
    exit(1)

#root=tk.Tk()
#cdf ="Code Dark Configurator"
#root.title("")
#headliner = tk.Label(root, text=cdf, font=(fontfamily, fontsize + 1))
#headliner.grid(sticky=tk.W + tk.N, row=rowvar, column=0)
#if cdw_version != "":
#    version = tk.Label(root, text="Code Dark Version: " + cdw_version, font=(fontfamily, fontsize + 1))
#    version.grid(sticky=tk.W + tk.N, row=rowvar, column=1)
#rowvar = rowvar + 1
#rowvar = add_label("============================================================", rowvar, 0)
#rowvar = rowvar + 1
#
#rowvar = add_section_label("DICOM PARAMETERS", rowvar)
#port_entry, rowvar = add_label_entry("Listening Port", aetp_data[PT], rowvar, 16)
#aet_entry, rowvar = add_label_entry("AET", aetp_data[AE], rowvar, 16)
#rowvar = rowvar + 1
#rowvar = add_label("============================================================", rowvar, 0)
#
#rowvar = add_section_label("AUTHORIZED RADIOLOGISTS", rowvar)
#rowvar = add_label("Edit List (this is a comma separated list so do not use any commas in names)", rowvar, 0)
#plist = json_data[PH]
#pbox, rowvar = add_box(', '.join(plist), rowvar)
#
#btn = tk.Button(root, text="Save and Exit", command=save_n_exit)
#btn.grid(sticky=tk.W+tk.S, row=rowvar + 3, column=0)

""" Begin Main Code section """

class TopWindow(Gtk.ApplicationWindow):
    def __init__(self, **kargs):
        super().__init__(**kargs, title="TopWindow")

        self.set_title("Code Dark Configurator")

        topbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
        self.set_child(topbox)

        """ DICOM parameters """
        line = 0
        frame = Gtk.Frame(label="DICOM PARAMETERS")
        topbox.append(frame)
        grid = Gtk.Grid()
        frame.set_child(grid)

        label = Gtk.Label(label="Listening Port")
        label.props.xalign = 0.0
        label.props.yalign = 0.5
        grid.attach(label, 0, line, 1, 1)
        self.pt_entry = Gtk.Entry(text=str(aetp_data[PT]))
        grid.attach(self.pt_entry, 1, line, 1, 1)
        line = line + 1

        label = Gtk.Label(label="AET")
        label.props.xalign = 0.0
        label.props.yalign = 0.5
        grid.attach(label, 0, line, 1, 1)
        self.ae_entry = Gtk.Entry(text=aetp_data[AE])
        grid.attach(self.ae_entry, 1, line, 1, 1)
        line = line + 1

        """ Authorized Physician List """
        frame = Gtk.Frame(label="AUTHORIZED RADIOLOGISTS")
        topbox.append(frame)
        grid = Gtk.Grid()
        frame.set_child(grid)

        line = 1
        label = Gtk.Label(label="Edit List (this is a comma separated list so do not use any commas in names)")
        label.props.xalign = 0.0
        label.props.yalign = 0.0
        grid.attach(label, 0, line, 1, 1)
        line = line + 1

        # Create the Textbuffer and load with data
        self.buffer = Gtk.TextBuffer()
        plist = json_data[PH]
        self.buffer.set_text(', '.join(plist))

        # Create the TextView (displays the data)
        self.textview = Gtk.TextView(buffer=self.buffer)
        self.textview.set_wrap_mode(Gtk.WrapMode.WORD) # Enable text wrapping
        self.textview.set_editable(True)
        
        # Add to ScrolledWindow for scrolling capability
        scrolled_window = Gtk.ScrolledWindow()
        scrolled_window.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.ALWAYS)
        scrolled_window.set_has_frame(True)
        scrolled_window.set_child(self.textview)
        grid.attach(scrolled_window, 0, line, 1, 1)

        """ Save and Quit button """
        line = 0
        frame = Gtk.Frame(label=None)
        topbox.append(frame)
        grid = Gtk.Grid()
        frame.set_child(grid)

        button = Gtk.Button(label="Save and Quit")
        grid.attach(button, 0, line, 1, 1)
        button.connect('clicked', self.save_n_exit)
        line = line + 1

    def save_n_exit(self, button):
        """ Non-json configuration items """
        """ None any more """
        """ Changed configuration items """
        aetp_changed = False
        port = int(self.pt_entry.get_text())
        if aetp_data[PT] != port:
            aetp_data[PT] = port
            aetp_changed = True

        aet = self.ae_entry.get_text()
        if aetp_data[AE] != aet:
            aetp_data[AE] = aet
            aetp_changed = True

        json_changed = False
        si = self.buffer.get_start_iter()
        ei = self.buffer.get_end_iter()
        pboxstr = self.buffer.get_text(si, ei, False)
        newp = [x.strip() for x in pboxstr.split(",")]
        if json_data[PH] != newp:
            json_data[PH] = newp
            json_changed = True

        if aetp_changed:
            with open(aetpfile, "w") as ofile:
                json.dump(aetp_data, ofile, indent=2)
                print("", file=ofile)
            try:
                result = subprocess.run(["/usr/bin/sudo", "-n", "systemctl", "restart", "orthanc"], capture_output=True, text=True)
                if result.returncode != 0:
                    print("Error Restarting Orthanc", result.stderr)
            except subprocess.CalledProcessError as e:
                print("Error restarting Orthanc", e.output)

        if json_changed:
            with open(jsonfile, "w") as ofile:
                json.dump(json_data, ofile, indent=2)
                print("", file=ofile)
                print("Other configuration data has changed. Restart any currently open report editing sessions.")
        exit(0)
        
def top_on_activate(app):
    win = TopWindow(application=app) 
    win.present()

app = Gtk.Application(application_id="org.github.zorkohiro.cdpw.code_dark_study_tool.top")
app.connect("activate", top_on_activate)
app.run(None)
