#!/usr/bin/python3
#
# Program to put up a set up of menus about selecting studies to operate on
#

import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk
import os
import sys
import fcntl
import json
import requests
import subprocess
import argparse
import logging

""" Variables and Constants """
REPORTDIR = "/code_dark/reports"
LOG = "/code_dark/logs/study_tool.log"
STUDYURL = "http://localhost:8042/studies"
THIS_STUDY_URL_PREFIX = "http://localhost:8042/app/explorer.html#study?uuid="
PATIENT_COL = 0
MRN_COL = 1
SESSION_NUMBER_COL = 2
STUDY_DESCRIPTION_COL = 3
STUDY_DATE_COL = 4
LAST_DICOM_DATA_COL = STUDY_DATE_COL

browser = "firefox"
spawn_editor = "cdpw_spawn_editor"
NoStudies = "No such studies"
NoStudiesPresent = "No studies present"
CannotReview = "Cannot Open"
StudiesToReview = "Studies To Begin Reviewing"
StudiesToEdit = "Studies to Continue Reviewing"
StudiesToSign = "Studies ready to sign"
StudiesToPrint = "Signed studies ready to print"
DeleteUnsigned = "Delete started but unsigned reports"
ListAllStudies = "List All Studies"
SubWindowActive = "Only one subordinate activity at a time allowed"

subwindow_active = False

fontsize = 12
fontfamily = "Times"

#
# Process command line arguments if any
#
parser = argparse.ArgumentParser(description="Code Dark Report Entry Package")
parser.add_argument("-f", "--fontsize", help="Font Size (default 12)")
args = vars(parser.parse_args())
if args['fontsize']:
    fontsize = int(args['fontsize'])

logging.basicConfig(filename=LOG, filemode="a", encoding="utf-8", format="{asctime} - {levelname} - {message}",
    style="{", datefmt="%m/%d/%Y %H:%M", level=logging.INFO)
logger = logging.getLogger(__name__)
logger.info("Code Dark Study Tool started")

""" Misc functions """

def message_showerr(message="An error occurred"):
    win = Gtk.Window()
    dialog = Gtk.AlertDialog()
    dialog.set_message("Error")
    dialog.set_detail(message)
    dialog.set_buttons(["OK"])
    dialog.show(parent=win)

def message_showinfo(message="A piece of information is available"):
    win = Gtk.Window()
    dialog = Gtk.AlertDialog()
    dialog.set_message("Info")
    dialog.set_detail(message)
    dialog.set_buttons(["OK"])
    dialog.show(parent=win)

def log_n_print(s):
    print(s)
    logger.info(s)

""" Button handlers """
def show_dicom(button, uuid, js):
    win = Gtk.Window()
    win.set_title("DICOM Data for Orthanc Study " + uuid)
    tv = Gtk.TextView()
    tv.set_editable(False)
    tv.set_cursor_visible(False)
    bf = tv.get_buffer()
    bf.set_text(json.dumps(js, indent=4))

    scrolled_window = Gtk.ScrolledWindow()
    scrolled_window.set_size_request(800, 500)
    scrolled_window.set_child(tv)
    win.set_child(scrolled_window)
    win.present()

def edit_report(button, uuid):
    log_n_print("edit_report for " + str(uuid))
    log_n_print("spawning browser" + " " + THIS_STUDY_URL_PREFIX + str(uuid))
    os.spawnlp(os.P_NOWAIT, browser, browser, THIS_STUDY_URL_PREFIX + str(uuid))
    log_n_print("spawning code_dark_rptgen")
    os.spawnlp(os.P_NOWAIT, "code_dark_rptgen", "code_dark_rptgen", "-j", REPORTDIR + "/" + str(uuid) + ".json")
    log_n_print("leaving edit_report")

def review_study(button, uuid):
    log_n_print("begin review of " + str(uuid))
    log_n_print("spawning browser")
    os.spawnlp(os.P_NOWAIT, browser, browser, THIS_STUDY_URL_PREFIX + str(uuid))
    log_n_print("spawning " + spawn_editor)
    os.spawnlp(os.P_NOWAIT, spawn_editor, spawn_editor, str(uuid))
    log_n_print("leaving review_study")


""" Study Table construction and presentation """

class TableWindow(Gtk.ApplicationWindow):
    def __init__(self, **kargs):
        title = kargs.pop("title", None)
        if not title:
            title = "Code Dark Study Tool"
        ulist = kargs.pop("uuid_list", None)
        button_handler = kargs.pop("button_handler", None)
        button_text = kargs.pop("button_text", None)
        super().__init__(**kargs, title=title)

        scrolled_window = Gtk.ScrolledWindow()
        scrolled_window.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        # Width is irrelevant since we are never scrolling width
        scrolled_window.set_size_request(400, 250)
        self.set_child(scrolled_window)

        grid = Gtk.Grid()
        grid.set_row_spacing(1)

        header = False
        rowvar = 0
        for suuid in ulist:
            srsp = requests.get(STUDYURL + "/" + suuid)
            if srsp.status_code != 200:
                continue

            try:
                result = subprocess.run(["GetStudyDate", "-r", suuid], capture_output=True, text=True)
                if result.returncode != 0:
                    logger.warning("cannot get study date for" + suuid + ":", result.returnconde)
                    continue
            except subprocess.CalledProcessError as e:
                logger.error("Error getting study date for" + suuid + ":", e.output)
                continue
            dst = result.stdout.strip()
            sjsn = srsp.json()
            patient = sjsn["PatientMainDicomTags"]
            maindcm = sjsn["MainDicomTags"]
            for pk in "PatientName","PatientID":
                try:
                    s = patient[pk]
                except:
                    patient[pk] = "<NIL>"
            for dk in "AcessionNumber":
                try:
                    s = maindcm[dk]
                except:
                    maindcm[dk] = "<NIL>"

            if header == False:
                frame = Gtk.Frame(label=None)
                label = Gtk.Label(label="Patient Name")
                label.set_markup("<b>Patient Name</b>")
                label.props.xalign = 0.0
                label.props.yalign = 1.0
                frame.set_child(label)
                grid.attach(frame, PATIENT_COL, rowvar, 1, 1)

                frame = Gtk.Frame(label=None)
                label = Gtk.Label(label="MRN")
                label.set_markup("<b>MRN</b>")
                label.props.xalign = 0.0
                label.props.yalign = 1.0
                frame.set_child(label)
                grid.attach(frame, MRN_COL, rowvar, 1, 1)

                frame = Gtk.Frame(label=None)
                label = Gtk.Label(label="Session Number")
                label.set_markup("<b>Session Number</b>")
                label.props.xalign = 0.0
                label.props.yalign = 1.0
                frame.set_child(label)
                grid.attach(frame, SESSION_NUMBER_COL, rowvar, 1, 1)

                frame = Gtk.Frame(label=None)
                label = Gtk.Label(label="Study Description")
                label.set_markup("<b>Study Description</b>")
                label.props.xalign = 0.0
                label.props.yalign = 1.0
                frame.set_child(label)
                grid.attach(frame, STUDY_DESCRIPTION_COL, rowvar, 1, 1)

                frame = Gtk.Frame(label=None)
                label = Gtk.Label(label="Study Date")
                label.set_markup("<b>Study Date</b>")
                label.props.xalign = 0.0
                label.props.yalign = 1.0
                frame.set_child(label)
                grid.attach(frame, STUDY_DATE_COL, rowvar, 1, 1)

                """ XXX Need a 'state' column here of where we are with this study """

                header = True
                rowvar = rowvar + 1

            """ Constant study related columns """
            frame = Gtk.Frame(label=None)
            label = Gtk.Label(label=patient["PatientName"])
            label.props.justify = Gtk.Justification.LEFT
            label.props.xalign = 0.0
            label.props.yalign = 1.0
            frame.set_child(label)
            grid.attach(frame, PATIENT_COL, rowvar, 1, 1)

            frame = Gtk.Frame(label=None)
            label = Gtk.Label(label=patient["PatientID"])
            label.props.justify = Gtk.Justification.LEFT
            label.props.xalign = 0.0
            label.props.yalign = 1.0
            frame.set_child(label)
            grid.attach(frame, MRN_COL, rowvar, 1, 1)

            frame = Gtk.Frame(label=None)
            label = Gtk.Label(label=maindcm["AccessionNumber"])
            label.props.justify = Gtk.Justification.LEFT
            label.props.xalign = 0.0
            label.props.yalign = 1.0
            frame.set_child(label)
            grid.attach(frame, SESSION_NUMBER_COL, rowvar, 1, 1)

            try:
                length = 30
                sd = maindcm["StudyDescription"]
                sdesc = sd[:length] + "..." if len(sd) > length else sd
            except:
                sdesc = ""

            frame = Gtk.Frame(label=None)
            label = Gtk.Label(label=sdesc)
            label.props.justify = Gtk.Justification.LEFT
            label.props.xalign = 0.0
            label.props.yalign = 1.0
            frame.set_child(label)
            frame.set_label_widget(None)
            grid.attach(frame, STUDY_DESCRIPTION_COL, rowvar, 1, 1)

            frame = Gtk.Frame(label=None)
            label = Gtk.Label(label=dst)
            label.props.justify = Gtk.Justification.LEFT
            label.props.xalign = 0.0
            label.props.yalign = 1.0
            frame.set_child(label)
            grid.attach(frame, STUDY_DATE_COL, rowvar, 1, 1)

            """ Action buttons """
            col = LAST_DICOM_DATA_COL + 1
            button = Gtk.Button(label="Show DICOM")
            button.connect('clicked', show_dicom, suuid, sjsn)
            grid.attach(button, col, rowvar, 1, 1)
            col = col + 1

            if button_handler != None:
                button = Gtk.Button(label=button_text)
                button.connect('clicked', button_handler, suuid)
                grid.attach(button, col, rowvar, 1, 1)

            rowvar = rowvar + 1

        scrolled_window.set_child(grid)

def present_table_on_activate(app, title, ulist, bhr, btxt):
    win = TableWindow(application=app, title=title, uuid_list=ulist, button_handler=bhr, button_text=btxt)
    win.present()
#
# Present the passed array of studies as a table with the passed title and some action buttons
# 
def present_table(title, ulist, button_handler, button_text):
    header = False
    app = Gtk.Application(application_id="org.github.zorkohiro.cdpw.code_dark_study_tool.present_table")
    app.connect("activate", present_table_on_activate, title, ulist, button_handler, button_text)
    rowvar = 0
    app.run(None)

def studies_to_review():
    """
    Begin review of studies that have not been reviewed yet

    A study is in this state if there is no <UUID>.json in /code_dark/reports.
    We have not looked at it at all.
    """
    global subwindow_active
    if subwindow_active:
        message_showerr(message=SubWindowActive)
        return
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        message_showerr(message=NoStudiesPresent)
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile) is False:
            out.append(uu)
    ns = len(out)
    if ns == 0:
        message_showinfo(message=NoStudies)
    else:
        rs = "Begin Review"
        print("subwindow_active True")
        subwindow_active = True
        if ns == 1:
            present_table("There is one study to begin reviewing", out, review_study, rs)
        else:
            present_table("There are " + str(ns) + " Studies to begin reviewing", out, review_study, rs)
        subwindow_active = False
        print("subwindow_active False")

def studies_to_edit():
    """
    Continue review of studies that have been reviewed at least partially already.

    A study is in this state if there is a <UUID>.json in /code_dark/reports and
    loading data from that json indicates that the study has not been signed.
    """
    global subwindow_active
    if subwindow_active:
        message_showerr(message=SubWindowActive)
        return
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        message_showerr("Cannot find any studies at all!")
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile):
            """ Now load report data the file for this study """
            json_data = []
            with open(jsfile, "r") as infile:
                json_data = json.load(infile)
            if not json_data["signed"]:
                out.append(uu)
    ns = len(out)
    if ns == 0:
        message_showinfo(message=NoStudies)
    else:
        es = 'Edit Study Report'
        subwindow_active = True
        if ns == 1:
            present_table("One Study to continue reviewing", out, edit_study_report, es)
        else:
            present_table(str(ns) + " Studies to continue reviewing", out, edit_report, es)
        subwindow_active = False

def studies_to_sign():
    """
    Find studies which are ready to sign as a list.

    A study is in this state if there is a <UUID>.json in /code_dark/reports and
    loading data from that json indicates that the study has met the criteria
    for being signed. The first criteria is that it is not now signed!
    """
    global subwindow_active
    if subwindow_active:
        message_showerr(message=SubWindowActive)
        return
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        message_showerr(message=NoStudiesPresent)
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile):
            """ Now load report data the file for this study """
            json_data = []
            with open(jsfile, "r") as infile:
                json_data = json.load(infile)
            if not json_data["signed"]:
                """ XXX GET OTHER CRITERIA- MAYBE HAVE AN EXTERNAL SCRIPT TO USE XXX """
                if json_data["signer"] != "":
                    out.append(uu)
    ns = len(out)
    if ns == 0:
        message_showinfo(message=NoStudies)
    else:
        subwindow_active = True
        if ns == 1:
            present_table("One Study ready for signing", out, None)
        else:
            present_table(str(ns) + " Studies ready for signing", out, None)
        subwindow_active = False

def studies_to_print():
    """
    Find studies which are ready to print.

    A study is in this state if there is a <UUID>.json in /code_dark/reports and
    loading data from that json indicates that the study has been signed
    but not printed.
    """
    global subwindow_active
    if subwindow_active:
        message_showerr(message=SubWindowActive)
        return
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        message_showerr(message=NoStudiesPresent)
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile):
            """ Now load report data the file for this study """
            json_data = []
            with open(jsfile, "r") as infile:
                json_data = json.load(infile)
            if json_data["signed"]:
                # Handle an older database which doesn't have the printed key
                try:
                    if not json_data["printed"]:
                        out.append(uu)
                except:
                    # If we don't have the printed key we'll assume it hasn't been printed
                    out.append(uu)
    ns = len(out)
    if ns == 0:
        message_showinfo(message=NoStudies)
    else:
        subwindow_active = True
        if ns == 1:
            present_table("One signed study ready for printing", out, None)
        else:
            present_table(str(ns) + " studies ready for printing", out, None)
        subwindow_active = False

def delete_report(button, uuid):
    print("delete_report for " + str(uuid))
    logger.info("delete_report for " + str(uuid))
    jsfile = REPORTDIR + "/" + str(uuid) + ".json"
    try:
        f = open(jsfile, "r")
    except FileNotFoundError:
        print("file", jsfile, "not found")
        logger.warning("file " + jsfile + " not found")
        message_showerr(message="Report File not found")
        return
    except Exception as e:
        print(f"exception: {e}")
        message_showerr(message="File Error")
        return
    # Make sure it isn't currently being edited
    lockfname = "/dev/shm/" + uuid + ".lock"
    locket = open(lockfname, "a")
    try:
        fcntl.flock(locket.fileno(), fcntl.LOCK_NB + fcntl.LOCK_EX);
    except OSError as e:
        if e.errno == errno.EACCES or e.errno == errno.EAGAIN:
            print(uuid, "already being edited")
            message_showerr("Error", "Study being edited")
        else:
            print(f"lock error {e}")
            message_showerr("Error", "Cannot access")
        f.close()
        locket.close()
        return
    os.unlink(jsfile)
    f.close()
    fcntl.flock(locket.fileno(), fcntl.LOCK_UN)
    locket.close()

def studies_to_delete():
    """
    List studies that have been started but have not been signed and put
    up a button to delete any reports in progess.

    A study is in this state if there is a <UUID>.json in /code_dark/reports and
    loading data from that json indicates that the study has not been signed.
    """
    global subwindow_active
    if subwindow_active:
        message_showerr(message=SubWindowActive)
        return
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        message_showerr("Cannot find any studies at all!")
        return
    sulist = response.json()

    out = []
    for uu in sulist:
        jsfile = REPORTDIR + "/" + uu + ".json"
        if os.path.exists(jsfile):
            """ Now load report data the file for this study """
            json_data = []
            with open(jsfile, "r") as infile:
                json_data = json.load(infile)
            if not json_data["signed"]:
                out.append(uu)
    ns = len(out)
    if ns == 0:
        message_showinfo(message=NoStudies)
    else:
        ds = 'Delete Report'
        subwindow_active = True
        if ns == 1:
            present_table("One possible report to delete", out, delete_report, ds)
        else:
            present_table(str(ns) + " possible reports to delete", out, delete_report, ds)
        subwindow_active = False

def all_studies():
    global subwindow_active
    if subwindow_active:
        message_showerr(message=SubWindowActive)
        return
    response = requests.get(STUDYURL)
    if response.status_code != 200:
        message_showerr(message="Cannot find any studies at all!")
    else:
        sulist = response.json()
        subwindow_active = True
        sulen = len(sulist)
        if sulen > 1:
            present_table("List All " + str(sulen) + " Studies", sulist, None, None)
        else:
            present_table("List the only study", sulist, None, None)
        subwindow_active = False

""" Begin Main Code section """

class TopWindow(Gtk.ApplicationWindow):
    def __init__(self, **kargs):
        super().__init__(**kargs, title="TopWindow")

        grid = Gtk.Grid()

        buttons = [
            StudiesToReview, StudiesToEdit,
            StudiesToSign, StudiesToPrint,
            DeleteUnsigned, ListAllStudies
        ]
        line = 0
        for button_name in buttons:
            button = Gtk.Button(label=button_name)
            button.set_hexpand(True)
            button.connect('clicked', self.handler, button_name)
            grid.attach(button, 0, line, 1, 1)
            line = line + 1

        button = Gtk.Button(label="Quit")
        grid.attach(button, 0, line, 1, 1)
        button.connect('clicked', self.leave)
        self.set_child(grid)


    def handler(self, button, arg):
        if arg == StudiesToReview:
           studies_to_review()
        elif arg == StudiesToEdit:
           studies_to_edit()
        elif arg == StudiesToSign:
           studies_to_sign()
        elif arg == StudiesToPrint:
           studies_to_print()
        elif arg == DeleteUnsigned:
           studies_to_delete()
        elif arg == ListAllStudies:
           all_studies()

    def leave(self, button):
        sys.exit(0)
        
def top_on_activate(app):
    win = TopWindow(application=app)
    win.present()

app = Gtk.Application(application_id="org.github.zorkohiro.cdpw.code_dark_study_tool.top")
app.connect("activate", top_on_activate)
app.run(None)
