#!/bin/bash
#
# Spawn the editor on a study UUID, e,g,:
#
#  spawn_editor uuid
#
# It there is no existing json in the report directory, this is
# this is the first time for this study, so invoke the tool that
# will help select the template to start from.
#

export PATH=/usr/bin:/usr/sbin
TPD=/usr/share/cdpw/Templates
CDB=/code_dark
RPT=${CDB}/reports
LOG=${CDB}/logs/spawn_editor.log

echo "=================================" >> ${LOG}
echo spawn_editor $* on `date` >> $LOG 2>&1
if [[ $# -ne 1 ]]; then
 echo "usage: $(basename $0) orthanc-uuid" >> $LOG
 exit 1
fi
uui=$1
mkdir -p ${RPT} >> $LOG 2>&1
fnm="${RPT}/${uui}.json"
prg=code_dark_rptgen
tpp=code_dark_select_template

if [[ ! -f "${fnm}" ]]; then
 # First time. Select a template with a python graphical tool
 type ${tpp}
 if [[ $? -ne 0 ]]; then
  echo ${tpp} does not exist in our path >> $LOG
  exit 1
 fi
 tpt=$(${tpp} $uui)
 inp="${TPD}/${tpt}"
 if [[ ! -f ${inp} ]]; then
  echo "${inp} does not exist- perhaps ${tpp} failed" >> $LOG
  exit 1
 fi
 #
 # Initial copy needs some values grafted in
 #
 sdt=$(GetStudyDate -r $uui)
 if [[ $sdt == "null" ]]; then sdt= ; fi
 dsc=$(curl -s http://localhost:8042/studies/${uui} | jq -r .MainDicomTags.StudyDescription)
 if [[ $dsc == "null" ]]; then dsc= ; fi
 ssn=$(curl -s http://localhost:8042/studies/${uui} | jq -r .MainDicomTags.AccessionNumber)
 if [[ $ssn == "null" ]]; then ssn= ; fi
 mrn=$(curl -s http://localhost:8042/studies/${uui} | jq -r .PatientMainDicomTags.PatientID)
 if [[ $mrn == "null" ]]; then mrn= ; fi
 sid=$(curl -s http://localhost:8042/studies/${uui} | jq -r .PatientMainDicomTags.StudyID)
 if [[ $sid == "null" ]]; then sid= ; fi
 rqp=$(curl -s http://localhost:8042/studies/${uui} | jq -r .PatientMainDicomTags.RequestingPhysician)
 if [[ $rqp == "null" ]]; then rqp= ; fi
 dob=$(curl -s http://localhost:8042/studies/${uui} | jq -r .PatientMainDicomTags.PatientBirthDate)
 if [[ -z "$dob" && "$dob" == "null" ]]; then
  yro=
 elif [[ -n "$dob" ]]; then
  short_sdt=$(GetStudyDate $uui | sed 1d | awk ' { print $2 }')
  if [[ -n "$short_sdt" && "$short_sdt" != "null" ]]; then
   yro=$(age_in_years $dob $short_sdt)
  else
   yro=
  fi
 fi
 echo running jq \
	".uuid = \"$uui\"" ${inp} '|' \
	jq ".date = \"$sdt\""        '|' \
	jq ".study_description = \"$dsc\"" '|' \
	jq ".mrn = \"$mrn\""         '|' \
	jq ".session = \"$ssn\""     '|' \
	jq ".studyid = \"$sid\""     '|' \
	jq ".doctor = \"$rqp\""      '|' \
	jq ".yrold = \"$yro\"" >> ${LOG}
 (jq \
	".uuid = \"$uui\"" ${inp}          |
	jq ".date = \"$sdt\""              |
	jq ".study_description = \"$dsc\"" |
	jq ".mrn = \"$mrn\""               |
	jq ".session = \"$ssn\""           |
	jq ".studyid = \"$sid\""           |
	jq ".doctor = \"$rqp\""            |
	jq ".yrold = \"$yro\"" > "${fnm}") 2>&1 >> ${LOG}
 if [[ $? -ne 0 ]]; then
  echo unable to create "$fnm" from $inp >> $LOG
  rm -f "${fnm}"
  exit 1
 fi
 chmod +w "$fnm"
else
 st=$(stat -c%A "${fnm}")
 echo "${fnm}" already exists with mode $st >> $LOG
fi

echo calling $prg -j "$fnm" on `date` >> $LOG
${prg} -j "$fnm"  >> $LOG 2>&1
if [[ $? -ne 0 ]]; then
 echo $prg exited witn non-zero status >> $LOG
fi
