#!/bin/bash
export DISPLAY=:0
export PATH=/usr/local/bin:/usr/bin:/usr/sbin
curu=$(who |grep '(:0)'|head -1|awk ' { print $1 }')
if [[ $curu != "orthanc" ]]; then
 echo calling sudo libreoffice $1 >> /tmp/sp.log
 sudo chown $curu $1
 sudo -n -u $curu libreoffice $1 >> /tmp/sp.log 2>&1
 echo $? was returned >> /tmp/sp.log
else
 echo calling libreoffice directly >> /tmp/sp.log
 libreoffice $1 >>  /tmp/sp.log 2>&1
fi
