Build Requirements
---------
Ubuntu 24.04 installed with:

build-essential, cmake, libjsoncpp-dev, uuid-dev, orthanc-dev

Build steps
--------
1. mkdir Build
2. cd Build
3. cmake .. -DALLOW_DOWNLOADS=ON -DCMAKE_BUILD_TYPE=Release
4. make
