#!/bin/bash

ORT=/etc/orthanc/orthanc.json
LOG=/code_dark/logs/CDPW.log
touch ${LOG} >/dev/null 2>&1 || LOG=/tmp/CDPW.log
echo CDPW_Configure starting on `date` >> $LOG

changed="no"

#
# Change database directory to code_dark- this
# is done at the very first startup after
# installing kp-report- this saves a copy
# of the orthanc.json config which gets
# restored if we remove the kp-report package.
#
# Note that DicomPort and DicomAet may also
# be changed by the code_dark_configurator
# tool. That change mechanism does no save
# of the configuration and the removal
# of kp-report will also restore DicomPort
# and DicomAet to the default.
#
grep -q /var/lib/orthanc/db-v6 ${ORT}
if [[ $? -eq 0 ]]; then
 echo setting orthanc database to /code_dark/database >> $LOG
 if [[ ! -f ${ORT}.save ]]; then
  cp ${ORT} ${ORT}.save
 fi
 sed -i 's,/var/lib/orthanc/db-v6,/code_dark/database,' ${ORT}
 changed="yes"
fi

#
# If we made any actual changes, restart Orthanc
#
if [[ $changed == "yes" ]]; then
 echo restarting orthanc >> $LOG
 systemctl daemon-reload
 sudo -n /usr/bin/restart_orthanc >> $LOG 2>&1
fi
