#!/bin/bash
if [[ -d /home/orthanc/Desktop ]]; then
 #
 # Make sure documentation linked to Orthanc desktop, if present
 #
 cp /dev/null /usr/lib/kp-report/idoc.txt
 for i in /usr/lib/kp-report/*.pdf; do
  n=/home/orthanc/Desktop/$(basename $i)
  rm -f $n
  ln -s $i $n
  echo $n >> /usr/lib/kp-report/idoc.txt
 done
 # XX: Disabled for now
 # Add the configurator desktop entry into Desktop
 #
 #cp /usr/lib/kp-report/code_dark_configurator.desktop /home/orthanc/Desktop
 #chown orthanc:orthanc /home/orthanc/Desktop/code_dark_configurator.desktop
 #gio set /home/orthanc/Desktop/code_dark_configurator.desktop metadata::trusted true
 # XX: Enabled instead:
 mkdir -p /home/orthanc/.local/share/applications
 chown orthanc:orthanc /home/orthanc/.local/share/applications
 cp /usr/lib/kp-report/code_dark_configurator.desktop /home/orthanc/.local/share/applications/code_dark_configurator.desktop
 chown orthanc:orthanc /home/orthanc/.local/share/applications/code_dark_configurator.desktop
fi 

#
# Clean up permissions
#
chown root:root /etc/sudoers.d/orthanc

#
# Give orthanc the ability to bind to privileged ports
#
setcap 'cap_net_bind_service=+ep' /sbin/Orthanc

#
# Enable cdpw_configure service
#
systemctl enable cdpw_configure.service

#
# Enable and restart orthanc_datamount service
#
systemctl enable orthanc_datamount_checker.service
systemctl restart orthanc_datamount_checker.service

#
# Explicitly exit with good status
#
exit 0
